checkoutButton: str = "//button[@id='checkout']"
txtFirstName: str = "//input[@placeholder='First Name']"
txtLastName: str = "//input[@placeholder='Last Name']"
txtZipCode: str = "//input[@placeholder='Zip/Postal Code']"
continueButton: str = "//input[@name='continue']"
subtotal: str = "//div[@class='summary_subtotal_label']"
finishButton: str = "//button[@id='finish']"
orderTitle: str = "//h2[@class='complete-header']"
orderMessage: str = "//div[@class='complete-text']"
backToHomeButton: str = "//button[@id='back-to-products']"