version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.11-browsers
    steps:
      - checkout

      - run:
          name: Set up Python virtual environment
          command: |
            python -m venv venv
            source venv/bin/activate

      - run:
          name: Install System Dependencies
          command: |
            echo 'Defaults    env_keep += "DEBIAN_FRONTEND"' | sudo tee -a /etc/sudoers
            sudo apt update && sudo apt install -y libssl-dev libffi-dev python3-dev build-essential

      - run:
          name: Install Rust
          command: |
            curl https://sh.rustup.rs -sSf | sh -s -- -y
            echo 'export PATH="$HOME/.cargo/bin:$PATH"' >> $BASH_ENV
            source $BASH_ENV
            rustc --version

      - run:
          name: Upgrade setuptools, wheel, and pip
          command: |
            pip install --upgrade setuptools wheel pip

      - run:
          name: Install dependencies
          command: |
            pip install --no-binary cryptography -r requirements.txt

      - run:
          name: Run Selenium Tests with pytest
          command: |
            pytest

workflows:
  version: 2
  build_and_test:
    jobs:
      - build