version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.11.5-browsers
    steps:
      - checkout
      - run:
          name: Set up Python virtual environment
          command: |
            python -m venv venv
            source venv/bin/activate
      - run:
          name: Install system dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y build-essential libssl-dev libffi-dev python3-dev
      - run:
          name: Install dependencies
          command: |
            pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Reinstall cryptography
          command: |
            pip uninstall -y cryptography
            pip install cryptography
      - run:
          name: Run Selenium Tests with pytest
          command: |
            pytest

workflows:
  version: 2
  build-test:
    jobs:
      - build