version: 2.1

jobs:
  test:
    docker:
      - image: python:3.11-browsers  # Use an appropriate Python version
    steps:
      - checkout
      - run:
          name: Install system dependencies
          command: |
            apt-get update && apt-get install -y \
            libssl-dev \
            rustc
      - run:
          name: Install Rust
          command: |
            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
            source $HOME/.cargo/env
      - run:
          name: Set up virtual environment
          command: |
            python -m venv venv
            source venv/bin/activate
      - run:
          name: Install setuptools-rust
          command: |
            pip install --upgrade setuptools wheel setuptools_rust
      - run:
          name: Install dependencies
          command: |
            pip install --upgrade pip
            pip install -r requirements.txt
            pip install --no-cache-dir --force-reinstall cryptography
      - run:
          name: Run pytest
          command: |
            pytest --ignore=env/Lib/site-packages/

workflows:
  version: 2
  test:
    jobs:
      - test
