version: 2.1

jobs:
  test:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout

      # Install system dependencies including browsers
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y wget unzip libnss3 libgconf-2-4 libxi6 libxrandr2 libasound2 libatk1.0-0 libcups2 fonts-liberation libxcomposite1 libxdamage1 libxext6 libxfixes3 libxinerama1 libpangocairo-1.0-0 libpangoft2-1.0-0 libx11-xcb1 libxcb1 libxkbcommon0 libxrender1 libxshmfence1

      # Install Rust (needed for cryptography package)
      - run:
          name: Install Rust
          command: |
            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
            echo 'source $HOME/.cargo/env' >> $BASH_ENV

      # Set up virtual environment
      - run:
          name: Set up virtual environment
          command: |
            python -m venv venv
            source venv/bin/activate

      # Install dependencies
      - run:
          name: Install Python dependencies
          command: |
            pip install --upgrade pip
            pip install -r requirements.txt
            pip install --no-cache-dir --force-reinstall cryptography

      # Run pytest
      - run:
          name: Run pytest
          command: |
            pytest --ignore=env/Lib/site-packages/

workflows:
  version: 2
  test:
    jobs:
      - test