version: 2.1

jobs:
  test:
    docker:
      - image: python:3.11  # Use an appropriate Python version
    steps:
      - checkout
      - run:
          name: Install system dependencies
          command: |
            apt-get update && apt-get install -y \
            libssl-dev \
            rustc
      - run:
          name: Set up virtual environment
          command: |
            python -m venv venv
            source venv/bin/activate
      - run:
          name: Install dependencies
          command: |
            pip install --upgrade pip
            pip install --no-cache-dir --force-reinstall cryptography
            pip install -r requirements.txt
      - run:
          name: Run pytest
          command: |
            pytest

workflows:
  version: 2
  test:
    jobs:
      - test
