version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.11.5-browsers
    steps:
      - checkout
      - run:
          name: Set up Python virtual environment
          command: |
            python -m venv venv
            source venv/bin/activate
      - run:
          name: Install Rust
          command: |
            apt update && apt install -y curl
            curl https://sh.rustup.rs -sSf | sh -s -- -y
            source $HOME/.cargo/env
      - run:
          name: Install dependencies
          command: |
            pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Run Selenium Tests with pytest
          command: |
            pytest

workflows:
  version: 2
  build-test:
    jobs:
      - build