name: Python CI with pytest and selenium

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.5'

      - name: Install Rust
        run: curl https://sh.rustup.rs -sSf | sh -s -- -y
        shell: bash

      - name: Upgrade pip, setuptools, and wheel
        run: |
          python -m pip install --upgrade pip setuptools wheel

      - name: Install Chrome and Firefox
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable firefox

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: pytest --browser chrome,firefox --ignore=env/Lib/site-packages/trio/_tests/
